"""
seed.py — build the corpus.

    python seed.py            plan only, writes nothing
    python seed.py --apply    write customers, orders and cases
    python seed.py --apply --embed   ... and embed everything after

Two sources of case text:

  - the hand-written hero cases in persona.py, which carry the demos and
    appear on camera
  - the rest generated by Nova Pro in batches from the persona brief

Generated batches are cached to .cache/generated/ keyed by sha256 of the
prompt, for the same reason embeddings are: a re-run after a crash should
cost nothing at Bedrock. Delete the cache to regenerate.

Cases are spread over ~6 months of opened_at so the corpus reads like a real
inbox rather than 300 tickets filed at the same instant.
"""

import argparse
import hashlib
import json
import os
import random
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import boto3

import db
import embeddings
import persona
import recall

CACHE = Path(__file__).parent / ".cache" / "generated"
TARGET_CASES = 300
SEED = 20260731  # fixed, so a re-run reproduces the same corpus

_s3 = None


def s3():
    global _s3
    if _s3 is None:
        _s3 = boto3.Session(
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            region_name=os.getenv("AWS_REGION", "eu-west-2"),
        ).client("s3")
    return _s3


def chat_model() -> str:
    m = os.getenv("BEDROCK_CHAT_MODEL")
    if not m:
        sys.exit("BEDROCK_CHAT_MODEL not set in .env")
    return m


# ------------------------------------------------------------------ generate

BATCH_PROMPT = """You are helping build a realistic test corpus for a customer \
support system. Invent {n} SEPARATE support messages sent to {business}, {trade}.

Setting: {setting}
Tone: {tone}

All {n} messages arrive on this channel: {channel}
Channel style: {style}

Spread them across these themes, roughly one message each:
{themes}

Rules:
- Each message is from a DIFFERENT customer about a DIFFERENT order.
- Write what the CUSTOMER wrote, not the reply.
- British English. Never mention being AI-generated.
- Vary length. Some are one line, some are a short paragraph.
- Do NOT use placeholder names like "Customer A" or "Item 1". Refer to real \
products a homeware shop sells.
- Order numbers, if mentioned, look like 4123 or ORD-4123.

Return STRICT JSON only, no prose, no code fence:
{{"cases":[{{"subject":"...","body":"...","theme":"...","resolution":"...",\
"outcome":"..."}}]}}

"resolution" is one sentence describing how staff resolved it, written after \
the fact. "outcome" is one of: refund, partial_refund, replacement, \
partial_replacement, exchange, goodwill, goodwill_discount, information, \
cancelled.
About one in six cases should still be open — for those, set "resolution" and \
"outcome" to null.
"""


def _cache_key(prompt: str, model: str) -> str:
    return hashlib.sha256(f"{model}|{prompt}".encode("utf-8")).hexdigest()


def generate_batch(channel: str, themes: list[str], n: int, model: str) -> list[dict]:
    """One Bedrock call for n cases on one channel. Cached to disk."""
    prompt = BATCH_PROMPT.format(
        n=n,
        business=persona.BUSINESS["name"],
        trade=persona.BUSINESS["trade"],
        setting=persona.BUSINESS["setting"],
        tone=persona.BUSINESS["tone"],
        channel=channel,
        style=persona.BUSINESS["channels"][channel],
        themes="\n".join(f"- {t}" for t in themes),
    )
    key = _cache_key(prompt, model)
    path = CACHE / f"{key}.json"
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))["cases"]

    rt = boto3.Session(
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name=os.getenv("AWS_REGION", "eu-west-2"),
    ).client("bedrock-runtime")

    resp = rt.converse(
        modelId=model,
        messages=[{"role": "user", "content": [{"text": prompt}]}],
        inferenceConfig={"maxTokens": 4096, "temperature": 0.9},
    )
    text = resp["output"]["message"]["content"][0]["text"].strip()

    # Nova sometimes wraps JSON in a fence despite being told not to.
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"no JSON object in model output: {text[:200]}")
    data = json.loads(text[start:end + 1])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=1), encoding="utf-8")
    return data["cases"]


# ---------------------------------------------------------------------- write

def upload_body(case_id: str, body: str) -> str | None:
    """Case body to S3; the key goes on the row. Vectors and pointers stay in
    CockroachDB, the artifact does not — the split the brief describes."""
    bucket = os.getenv("S3_BUCKET")
    if not bucket:
        return None
    key = f"cases/{case_id}.txt"
    s3().put_object(Bucket=bucket, Key=key, Body=body.encode("utf-8"),
                    ContentType="text/plain; charset=utf-8")
    return key


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="actually write rows")
    ap.add_argument("--embed", action="store_true", help="embed after seeding")
    ap.add_argument("--cases", type=int, default=TARGET_CASES)
    ap.add_argument("--force", action="store_true",
                    help="seed even if cases already holds rows")
    args = ap.parse_args()

    db.safe_console()
    rng = random.Random(SEED)
    model = chat_model()
    now = datetime.now(timezone.utc)

    print(f"business : {persona.BUSINESS['name']}")
    print(f"model    : {model}")
    print(f"target   : {args.cases} cases "
          f"({len(persona.HERO_CASES)} hand-written, "
          f"{args.cases - len(persona.HERO_CASES)} generated)")
    print("-" * 70)

    # --- generate the bulk, one batch per channel per round -----------------
    need = args.cases - len(persona.HERO_CASES)
    per_batch = 10
    generated: list[dict] = []
    channels = list(persona.BUSINESS["channels"])
    theme_names = [t for t, _ in persona.THEMES]

    round_no = 0
    while len(generated) < need:
        ch = channels[round_no % len(channels)]
        themes = rng.sample(theme_names, k=min(per_batch, len(theme_names)))
        try:
            batch = generate_batch(ch, themes, per_batch, model)
        except Exception as e:  # noqa: BLE001
            print(f"[FAIL] batch {round_no} ({ch}): "
                  f"{type(e).__name__}: {str(e).splitlines()[0][:110]}")
            round_no += 1
            if round_no > need // per_batch + 20:
                sys.exit("too many generation failures — stopping")
            continue
        for c in batch:
            c["channel"] = ch
        generated.extend(batch)
        print(f"  batch {round_no:>2} {ch:<9} +{len(batch):>2} "
              f"(total {len(generated)}/{need})")
        round_no += 1

    generated = generated[:need]
    print("-" * 70)

    if not args.apply:
        print("PLAN ONLY — nothing written. Re-run with --apply.")
        sample = generated[0] if generated else {}
        print(f"\nsample generated case ({sample.get('channel')}):")
        print(f"  subject   : {sample.get('subject')}")
        print(f"  body      : {(sample.get('body') or '')[:160]}")
        print(f"  resolution: {sample.get('resolution')}")
        return

    # --- write ------------------------------------------------------------
    with db.connect() as conn:
        cur = conn.cursor()

        for ref, name in persona.CUSTOMERS:
            slug = name.lower().replace(" ", ".").replace("'", "")
            cur.execute(
                "INSERT INTO customers (customer_ref, display_name, email) "
                "VALUES (%s,%s,%s) ON CONFLICT (customer_ref) DO NOTHING",
                (ref, name, f"{slug}@example.com"),
            )
        print(f"customers: {len(persona.CUSTOMERS)}")

        # Hero orders first — the demos reference these ids by name.
        for oid, ref, item, amount, days in persona.HERO_ORDERS:
            cur.execute(
                "INSERT INTO orders (order_id, customer_ref, placed_at, item, "
                "amount_minor) VALUES (%s,%s,%s,%s,%s) "
                "ON CONFLICT (order_id) DO NOTHING",
                (oid, ref, now - timedelta(days=days), item, amount),
            )

        # Background orders, so the hero ones are not conspicuously alone.
        made = 0
        for i in range(60):
            oid = f"ORD-{4100 + i}"
            if any(oid == h[0] for h in persona.HERO_ORDERS):
                continue
            ref = rng.choice(persona.CUSTOMERS)[0]
            item, price = rng.choice(persona.ITEMS)
            cur.execute(
                "INSERT INTO orders (order_id, customer_ref, placed_at, item, "
                "amount_minor) VALUES (%s,%s,%s,%s,%s) "
                "ON CONFLICT (order_id) DO NOTHING",
                (oid, ref, now - timedelta(days=rng.randint(2, 180)), item, price),
            )
            made += 1
        print(f"orders   : {len(persona.HERO_ORDERS)} hero + {made} background")

        # Seeding twice would double the corpus and quietly wreck the index
        # evidence, so refuse rather than append.
        cur.execute("SELECT count(*) FROM cases")
        existing = cur.fetchone()[0]
        if existing and not args.force:
            sys.exit(
                f"cases already holds {existing} row(s). Seeding again would "
                f"duplicate it.\nRe-run with --force to add anyway, or clear "
                f"the table first."
            )

        INSERT_CASE = """
            INSERT INTO cases (channel, customer_ref, subject, body,
                   resolution, outcome, opened_at, resolved_at)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
            RETURNING case_id
        """

        def resolved_stamp(resolution, opened, hours):
            """A case is resolved iff it has resolution text — the CHECK
            constraint enforces exactly that, so derive one from the other
            rather than letting them drift apart."""
            return None if resolution is None else opened + timedelta(hours=hours)

        # Hero cases.
        hero_ids = []
        for c in persona.HERO_CASES:
            opened = now - timedelta(days=c["days_ago"])
            cur.execute(INSERT_CASE, (
                c["channel"], c["customer_ref"], c["subject"], c["body"],
                c["resolution"], c["outcome"], opened,
                resolved_stamp(c["resolution"], opened, 20),
            ))
            hero_ids.append((str(cur.fetchone()[0]), c["body"]))

        # Generated cases, spread over ~6 months.
        gen_ids = []
        for c in generated:
            body = (c.get("body") or "").strip()
            if not body:
                continue
            res = c.get("resolution") or None
            opened = now - timedelta(days=rng.randint(2, 180))
            cur.execute(INSERT_CASE, (
                c["channel"], rng.choice(persona.CUSTOMERS)[0],
                (c.get("subject") or "").strip()[:200], body,
                res, c.get("outcome") or None, opened,
                resolved_stamp(res, opened, rng.randint(2, 72)),
            ))
            gen_ids.append((str(cur.fetchone()[0]), body))

        print(f"cases    : {len(hero_ids)} hero + {len(gen_ids)} generated")

        # Artifacts to S3, pointer back on the row.
        uploaded = 0
        for cid, body in hero_ids + gen_ids:
            key = upload_body(cid, body)
            if key:
                cur.execute("UPDATE cases SET s3_key=%s WHERE case_id=%s", (key, cid))
                uploaded += 1
        print(f"s3       : {uploaded} bodies uploaded to "
              f"{os.getenv('S3_BUCKET')}")

        cur.execute("SELECT count(*) FROM cases")
        print(f"corpus   : {cur.fetchone()[0]} rows total")

    if args.embed:
        print("-" * 70)
        n = recall.backfill()
        print(f"embedded : {n} case(s)")
        files, size = embeddings.cache_stats()
        print(f"cache    : {files} vectors, {size/1024:.0f} KB")


if __name__ == "__main__":
    main()
